version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: biolink_api
            MYSQL_USER: biolink
            MYSQL_PASSWORD: biolink
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
